version: "3"

tasks:
  build:
    desc: Build Docker images (without starting containers)
    cmds:
      - docker compose -f infra/docker-compose.yml --env-file .env build

  up:
    desc: Start containers (without rebuilding images)
    cmds:
      - docker compose -f infra/docker-compose.yml --env-file .env up -d

  down:
    desc: Stop and remove containers
    cmds:
      - docker compose -f infra/docker-compose.yml --env-file .env down

  migrate:
    desc: Run database migrations (Flyway)
    cmds:
      - docker compose -f infra/docker-compose.yml --env-file .env run --rm migrations

  logs:
    desc: API logs (follow mode)
    cmds:
      - docker logs -f mh_api

  psql:
    desc: Access PostgreSQL shell inside the db container
    cmds:
      - docker exec -it mh_db psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}}
    vars:
      POSTGRES_USER: { sh: "grep POSTGRES_USER .env | cut -d '=' -f2" }
      POSTGRES_DB: { sh: "grep POSTGRES_DB .env | cut -d '=' -f2" }

  restart:
    desc: Restart the stack (infra + api)
    cmds:
      - task: down
      - task: up
